### ISSUE TITLE
Error reported on axum version 0.6.1

### ISSUE THREAD

**Issue by wangeguo** [benwis/tower-governor#1]
Hi, first of all thank you for such a useful crate, when I upgraded axum to 0.6.1 it apparently had a compatibility issue, see the log below for details:

```
error[E0277]: the trait bound `GovernorLayer<'_, PeerIpKeyExtractor, governor::middleware::StateInformationMiddleware>: Clone` is not satisfied
   --> src/main.rs:50:9
    |
49  |       let app = routes::build().layer(Extension(database)).layer(
    |                                                            ----- required by a bound introduced by this call
50  | /         ServiceBuilder::new()
51  | |             .layer(HandleErrorLayer::new(|err: BoxError| async move {
52  | |                 (
53  | |                     StatusCode::INTERNAL_SERVER_ERROR,
...   |
58  | |                 config: &governor_conf,
59  | |             }),
    | |______________^ the trait `Clone` is not implemented for `GovernorLayer<'_, PeerIpKeyExtractor, governor::middleware::StateInformationMiddleware>`
    |
    = note: required for `GovernorLayer<'_, PeerIpKeyExtractor, governor::middleware::StateInformationMiddleware>` to implement `Clone`
    = note: 2 redundant requirements hidden
    = note: required for `ServiceBuilder<Stack<GovernorLayer<'_, PeerIpKeyExtractor, governor::middleware::StateInformationMiddleware>, Stack<..., ...>>>` to implement `Clone`
note: required by a bound in `Router::<S, B>::layer`
   --> /Users/wangeguo/.cargo/registry/src/mirrors.ustc.edu.cn-12df342d903acd47/axum-0.6.1/src/routing/mod.rs:316:30
    |
316 |         L: Layer<Route<B>> + Clone + Send + 'static,
    |                              ^^^^^ required by this bound in `Router::<S, B>::layer`
help: consider borrowing here
    |
50  |         &ServiceBuilder::new()
    |         +

For more information about this error, try `rustc --explain E0277`.
```

**Comment by benwis** [comment]
Glad you're enjoying it!
Yeah, with Axum 0.6 Layers must now implement `Clone`. I've updated the example to show how to do that,  the easiest way is to `Box` the governor_config and then leak it. 

I've updated the basic example and released a new version with updated dependencies.

**Comment by wangeguo** [comment]
It still looks wrong, I checked your example and found that axum in cargo.toml is still 0.5.16

**Comment by benwis** [comment]
Apologies, I screwed up the transfer. Pretty sure it's right now
